[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
astropy = "^6.1.2"
matplotlib = "^3.9.2"
matplotlib-venn = "^1.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
